{% set version = "0.6.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-padr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/padr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/padr/padr_{{ version }}.tar.gz
  sha256: 27f14a461d7bed2fa45865090066849fb0c08777ea25a36f0535492fd46ef255

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-lubridate                # [build_platform != target_platform]
    - r-rlang                    # [build_platform != target_platform]
    - r-dplyr                    # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-dplyr >=1.0.0
    - r-lubridate
    - r-rlang
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-dplyr >=1.0.0
    - r-lubridate
    - r-rlang

test:
  commands:
    - $R -e "library('padr')"           # [not win]
    - "\"%R%\" -e \"library('padr')\""  # [win]

about:
  home: https://github.com/EdwinTh/padr
  license: MIT
  license_file: LICENSE
  summary: 'Transforms datetime data into a format ready for analysis. It offers two core functionalities; aggregating data to a higher level interval (thicken) and imputing records where observations were absent (pad). '
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: padr
# Type: Package
# Title: Quickly Get Datetime Data Ready for Analysis
# Version: 0.4.1
# Author: Edwin Thoen
# Maintainer: Edwin Thoen <edwinthoen@gmail.com>
# Description: Transforms datetime data into a format ready for analysis. It offers two core functionalities; aggregating data to a higher level interval (thicken) and imputing records where observations were absent (pad).
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.0.0)
# Imports: Rcpp, dplyr (>= 0.6.0), lubridate, rlang
# Suggests: ggplot2, testthat, knitr, rmarkdown, lazyeval, tidyr, data.table, lintr
# RoxygenNote: 6.0.1
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# URL: https://github.com/EdwinTh/padr
# BugReports: https://github.com/EdwinTh/padr/issues
# ByteCompile: true
# NeedsCompilation: yes
# Packaged: 2018-06-26 10:12:45 UTC; edwinthoen
# Repository: CRAN
# Date/Publication: 2018-06-26 19:23:11 UTC
