appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: EPQkIChXDQ/ZuTLho1ZHIwgoLZ4MGJEmNkrPhJP9lTuzo18LZaqgsKRHl67P6pSXMdk436KYEaqMmiQOKd760mXEZ5ecNeHqUNbRsHQOTwnJc4cvk2BKJtp/2iNG/58AFqMONk9Ad/k/ODl+3rLj4/4ghtgsGQO+mFsywfwh7l09Ta1UWz0jZh/r6rtMOXC0gD9nV+MKpq4w8sAe2V+Q8qXbFcyST/aOxNy3uGajr7QYbOfz4dCsPNYCAItI5aVa1CpJY0jbMVJAgvQIYIRaHaeGCIR5KgfMQfhLP5ttor/gk4l2EydU3E0VgsTlGqMCrPPoP/3FPKA9MEYveUooCGV2AcmoE7UieasiuKXT+PnS78vrXnVA4WvfvVl96D7xHcKz4b+keGHjAiNBtrjA1mttxvFaiag5j1u1aTiN5FQbXQtVBxU97qCysv7N08q3fwPqrgWL1p160JVtSYy4Xt0VU2OojVpFM4oETq/cl1nXPp8DthEZH19UUnEI0TyiCq1pKvn4IbZSzMz8qNS2g3MUsWoRjVe6EWLFK18jH7slWdk83UxwxBLs4EVZFpB6vr5wHz+9aCMnOeJp0fgtaPouRLjvfYBoi5vIgBUH9whcMNGc4YFQR39zZQPSLsOGy1Tmf7zMgP0EdNMJhYEkyzUWjVBXZxMP3QwPJPYGxOs=}
